language: objective-c
os: osx
osx_image: xcode9.2
notifications:
    email: false

env:
    global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=XlsxReaderWriter.xcworkspace
    - IOS_SCHEME="XlsxReaderWriter"
    - IOS_SDK=iphonesimulator11.2
    - IOS_DEST="OS=11.2,name=iPhone X"

    matrix:
    - DESTINATION="$IOS_DEST" SCHEME="$IOS_SCHEME" SDK="$IOS_SDK" RUN_TESTS="YES"

script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c